services:
  media_services:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 10gb
    devices:
      - '/dev/snd:/dev/snd'
    #   - /dev/bus/:/dev/bus
    # network_mode: "host"
    privileged: true
    restart: always
    volumes:
      - '/run/user/1000/pulse:/run/user/1000/pulse'
      - './client.conf:/etc/pulse/client.conf'
      - './daemon.conf:/etc/pulse/daemon.conf'
      - './default.pa:/etc/pulse/default.pa'
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ./run.log:/workspace/run.log
    environment:
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - BROKER=192.168.1.98
    working_dir: /workspace
    command: bash -c "python Playing_service.py"
    # command: bash -c "tail -f > /dev/null"
